[package]
name = "gdal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ndarray.workspace = true
rayon.workspace = true
chrono.workspace = true
gdal-rs.workspace = true
gdal-sys = "0.12"
thiserror.workspace = true
anyhow.workspace = true
regex.workspace = true

[dev-dependencies]
approx.workspace = true
