[package]
name = "nufrost-gdal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nufrost-core = { path = "../nufrost-core" }
ndarray.workspace = true
rayon.workspace = true
chrono.workspace = true
gdal.workspace = true
thiserror.workspace = true
anyhow.workspace = true

[dev-dependencies]
approx.workspace = true
